name: Saturday Deep Clean

on:
  schedule:
    # 9:00 AM New York
    # EDT: 13:00 UTC, EST: 14:00 UTC
    - cron: "0 13 * * 6"
    - cron: "0 14 * * 6"
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install luxon
        run: npm install luxon

      - name: Show workspace (once, for sanity)
        run: ls -la

      - name: Run weekly rotation
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}   # topic ONLY (no https://)
          # NTFY_SERVER: ${{ secrets.NTFY_SERVER }}  # only if self hosted
          # BYPASS_GATE: "1"  # <- uncomment for a one-time immediate test
        run: node deep_clean.js
