name: Saturday Deep Clean

on:
  schedule:
    # Run at :00 past 13:00 and 14:00 UTC on Saturdays.
    # The script gates to only send at 9:00 AM America/New_York.
    - cron: "0 13 * * 6"
    - cron: "0 14 * * 6"
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install luxon
        run: npm install luxon

      - name: Run rotation script
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          # Optional: point to your own server if you self-host ntfy
          # NTFY_SERVER: ${{ secrets.NTFY_SERVER }}
        run: node deep_clean.js

      # .github/workflows/deep-clean.yml
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install luxon
      - name: Run rotation script
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}   # topic ONLY, no https://ntfy.sh/
          BYPASS_GATE: "1"                        # <— TEMP: forces send now
        run: node scripts/deep_clean.js

